version: '3'

services: 
  flaskapp:
    build: ./flaskapp-docker
    container_name: flaskapp
    # ports: 
    #   - "8000:8000"
    # network_mode: host
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_CONFIG_FILE=/aws/credentials
      - AWS_PROFILE=csloginstudent
  
  nginx:
    build: ./nginx
    container_name: nginx
    environment: 
      - SERVER_NAME=54.242.214.218
    ports: 
      - "80:80"
    restart: always
    network_mode: host
  
  networks: 
    default:
      driver: bridge
  
