version: '3'

services: 
  flaskapp:
    build: ./flaskapp-docker
    ports: 
       - "5001-5006:5000"
    environment:
      - AWS_SHARED_CREDENTIALS_FILE=/aws/credentials
      - AWS_CONFIG_FILE=/aws/credentials
      - AWS_PROFILE=csloginstudent
  
  nginx:
    image: nginx:latest
    container_name: nginx
    environment: 
      - SERVER_NAME=54.242.214.218
    ports: 
      - "80:80"
    restart: unless-stopped
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
